module:
  address: 0
  admin_styles: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  anchor_exposed_filter: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_entity_updates: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_clone: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_collection: 0
  field_group: 0
  field_group_migrate: 0
  field_ui: 0
  file: 0
  filter: 0
  flippy: 0
  geofield: 0
  help: 0
  history: 0
  image: 0
  kint: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  layout_library: 0
  lazy: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_file_to_media: 0
  migrate_file_to_media_example: 0
  migrate_media: 0
  migrate_plus: 0
  migrate_tools: 0
  moderation_sidebar: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pixeloid_ckeditor_quote: 0
  project_view_mode: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  seckit: 0
  shortcut: 0
  styled_google_map: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_extensions: 0
  twig_vardumper: 0
  unified_twig_ext: 0
  update: 0
  user: 0
  vem_migrate_oembed: 0
  video_embed_field: 0
  video_embed_media: 0
  views_block_filter_block: 0
  views_ui: 0
  weight: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  t1: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: hu
profile: null
