definitions:
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
langcode: hu
