flippy_project: 1
flippy_head_project: 0
flippy_show_empty_project: 0
flippy_prev_label_project: 'Previous project'
flippy_next_label_project: 'Next project'
flippy_first_last_project: 0
flippy_first_label_project: ''
flippy_last_label_project: ''
flippy_loop_project: 0
flippy_random_project: 0
flippy_random_label_project: ''
flippy_truncate_project: ''
flippy_ellipse_project: ''
flippy_custom_sorting_project: 1
flippy_sort_project: field_weight
flippy_order_project: ASC
flippy_partner: 0
flippy_head_partner: 0
flippy_show_empty_partner: 0
flippy_prev_label_partner: ''
flippy_next_label_partner: ''
flippy_first_last_partner: 0
flippy_first_label_partner: ''
flippy_last_label_partner: ''
flippy_loop_partner: 0
flippy_random_partner: 0
flippy_random_label_partner: ''
flippy_truncate_partner: ''
flippy_ellipse_partner: ''
flippy_press_swipe_partner: null
flippy_custom_sorting_partner: 0
flippy_sort_partner: nid
flippy_order_partner: ASC
flippy_team_member: 0
flippy_head_team_member: 0
flippy_show_empty_team_member: 0
flippy_prev_label_team_member: ''
flippy_next_label_team_member: ''
flippy_first_last_team_member: 0
flippy_first_label_team_member: ''
flippy_last_label_team_member: ''
flippy_loop_team_member: 0
flippy_random_team_member: 0
flippy_random_label_team_member: ''
flippy_truncate_team_member: ''
flippy_ellipse_team_member: ''
flippy_press_swipe_team_member: null
flippy_custom_sorting_team_member: 0
flippy_sort_team_member: nid
flippy_order_team_member: ASC
