image_fields:
  media--image--field_media_image--hero: '1'
  media--image--field_media_image--grid_item: '1'
alter_tag:
  img: img
  iframe: '0'
formatters:
  lazy_image: '0'
  lazy_responsive_image: '0'
skipClass: no-lazy
disabled_paths: /rss.xml
placeholderSrc: ''
preferNative: false
lazysizes:
  lazyClass: lazyload
  loadedClass: lazyloaded
  loadingClass: lazyloading
  preloadClass: lazypreload
  errorClass: lazyerror
  autosizesClass: lazyautosizes
  srcAttr: data-src
  srcsetAttr: data-srcset
  sizesAttr: data-sizes
  minSize: 40
  customMedia: {  }
  init: true
  expFactor: 1.5
  hFac: 0.8
  loadMode: 2
  loadHidden: true
  ricTimeout: 0
  throttleDelay: 125
  plugins: {  }
_core:
  default_config_hash: 1TShnSplWum3f2DJ6uq-OQsANqeYJVltsSdViV_YY7Y
langcode: hu
