features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: 'public://T1 kislogo 1.png'
  mimetype: image/png
