<?php

/**
 * @file
 * Contains twig_extensions.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twig_extensions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twig_extensions module.
    case 'help.page.twig_extensions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Twig extensions') . '</p>';
      return $output;

    default:
  }
}
